ap_scan=1 #1-default 2-scan only 0-no scan

country=UA
update_config=1

eapol_version=1
#: IEEE 802.1X-2004 - 1 (default)
#: 802.1X-2004/2010 - 2

filter_ssids=1
#: 0 = do not filter scan results (default)
#: 1 = only include configured SSIDs in scan results/BSS table


network={
	ssid="Chernienko2"
	psk="112345678"
	key_mgmt=WPA-PSK
	proto=RSN
	pairwise=CCMP
	group=CCMP
	scan_ssid=0 # 1 if ssid is hidden, 1 - no priority checking
	priority=2  #high for other networks with higher priority
}
